/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */

// @ts-check

/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  // By default, Docusaurus generates a sidebar from the docs folder structure
  // tutorialSidebar: [{type: 'autogenerated', dirName: '.'}],

  // But you can create a sidebar manually
  
  mainSidebar: [
    {
      type: 'doc',
      id: 'index',
    },
    {
      type: 'category',
      label: 'Getting Started',
      items: ['setup', 'examples', 'community-resources', 'configuration', 'migration', 'frequently-asked-questions'],
      collapsed: false,
    },
    {
      type: 'category',
      label: 'Documentation',
      items: ['udonsharp', 'vrchat-api', 'events', 'editor-scripting'],
      collapsed: true,
    },
    {
      type: 'category',
      label: 'Extra',
      items: ['random-tips-&-performance-pointers', 'runtime-exception-debugging', 'class-exposure-tree', 'networking-tips-&-tricks', 'using-vrc-stations', 'exporting-to-assembly-files'],
      collapsed: true,
    },
  ],
   
};

module.exports = sidebars;
